#!/usr/bin/env bash
# Render (and optionally apply) a monitoring tenant from k8s/tenants/_template.
#
#   scripts/add-tenant.sh <team>            render k8s/tenants/<team>/
#   scripts/add-tenant.sh <team> --apply    render and kubectl apply
#
# The rendered directory is plain YAML committed to git, so onboarding a
# tenant is a pull request. In a GitOps setup an Argo CD ApplicationSet
# with a directory generator over k8s/tenants/* deploys it on merge.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEMPLATE_DIR="${REPO_DIR}/k8s/tenants/_template"
TENANTS_DIR="${REPO_DIR}/k8s/tenants"

usage() { echo "usage: $0 <team-name> [--apply]" >&2; exit 2; }

TEAM="${1:-}"; [[ -n "$TEAM" ]] || usage
APPLY="${2:-}"

# Tenant name becomes a namespace, a Prometheus name and a label value, so
# it must be a DNS-1123 label.
if ! [[ "$TEAM" =~ ^[a-z0-9]([a-z0-9-]{0,30}[a-z0-9])?$ ]]; then
  echo "error: '$TEAM' is not a valid tenant name (lowercase DNS label, max 32 chars)" >&2
  exit 1
fi

OUT="${TENANTS_DIR}/${TEAM}"
if [[ -d "$OUT" ]]; then
  echo "tenant '$TEAM' already rendered at ${OUT#"$REPO_DIR"/}, re-rendering from template"
fi
mkdir -p "$OUT"

for f in "${TEMPLATE_DIR}"/*.yaml; do
  sed "s/TENANT/${TEAM}/g" "$f" > "${OUT}/$(basename "$f")"
done

{
  echo "# Generated by scripts/add-tenant.sh ${TEAM}. Edit the template, not this file."
  echo "apiVersion: kustomize.config.k8s.io/v1beta1"
  echo "kind: Kustomization"
  echo "resources:"
  for f in "${OUT}"/*.yaml; do
    [[ "$(basename "$f")" == "kustomization.yaml" ]] && continue
    echo "  - $(basename "$f")"
  done
} > "${OUT}/kustomization.yaml"

# Register the tenant in the aggregate kustomization (idempotent, sorted).
AGG="${TENANTS_DIR}/kustomization.yaml"
{
  echo "# Aggregates every tenant. Maintained by scripts/add-tenant.sh."
  echo "apiVersion: kustomize.config.k8s.io/v1beta1"
  echo "kind: Kustomization"
  echo "resources:"
  for d in "${TENANTS_DIR}"/*/; do
    n="$(basename "$d")"
    [[ "$n" == _* ]] && continue
    echo "  - ${n}"
  done | sort
} > "$AGG"

echo "rendered ${OUT#"$REPO_DIR"/}"

if [[ "$APPLY" == "--apply" ]]; then
  kubectl apply -k "$OUT"
  echo "waiting for prometheus-${TEAM}..."
  kubectl rollout status "statefulset/prometheus-${TEAM}" -n "team-${TEAM}" --timeout=180s
  echo "tenant '${TEAM}' is up. Federation target appears in the central Prometheus within 30s."
fi
