apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mock-service
  namespace: sre-challenge
  labels:
    tier: platform
spec:
  selector:
    matchLabels:
      app: mock-service
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
